import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import QRCode from 'qrcode';
import { createServer } from 'http';
import { Server } from 'socket.io';
import { randomUUID, createHmac } from 'crypto';
import db from './db.js';

dotenv.config();
const app=express(); const http=createServer(app); const io=new Server(http,{cors:{origin:'*'}});
app.use(cors()); app.use(express.json());
const SECRET=process.env.JWT_SECRET||'attendx-demo-secret';
const sign=u=>jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:'8h'});
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ','')||'x',SECRET);next()}catch{return res.status(401).json({message:'Authentication required'})}}
function distance(a,b,c,d){const R=6371000,rad=x=>x*Math.PI/180;const x=rad(c-a),y=rad(d-b);const h=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function audit(eventId,userId,action,reason=''){db.prepare('INSERT INTO audit_logs VALUES (?,?,?,?,?,?)').run(randomUUID(),eventId,userId,action,reason,new Date().toISOString())}

app.get('/api/health',(req,res)=>res.json({ok:true,service:'ATTENDX API'}));
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!bcrypt.compareSync(password,u.password))return res.status(401).json({message:'Invalid email or password'});res.json({token:sign(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post('/api/auth/register',(req,res)=>{const {name,email,password,role='attendee'}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});try{const id=randomUUID();db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,?)').run(id,name,email,bcrypt.hashSync(password,10),role,new Date().toISOString());const u=db.prepare('SELECT * FROM users WHERE id=?').get(id);res.json({token:sign(u),user:{id,name,email,role}})}catch(e){res.status(409).json({message:'Email already registered'})}});

app.get('/api/events',auth,(req,res)=>{let rows=req.user.role==='organizer'?db.prepare('SELECT * FROM events WHERE organizer_id=? ORDER BY start_time DESC').all(req.user.id):db.prepare('SELECT * FROM events ORDER BY start_time DESC').all();rows=rows.map(e=>({...e,total:db.prepare('SELECT COUNT(*) c FROM attendance WHERE event_id=? AND status="present"').get(e.id).c}));res.json(rows)});
app.post('/api/events',auth,(req,res)=>{if(req.user.role!=='organizer')return res.status(403).json({message:'Organizer only'});const {name,description,venue,latitude,longitude,radius=100,start_time,end_time}=req.body;if(!name||latitude==null||longitude==null||!start_time||!end_time)return res.status(400).json({message:'Missing event fields'});const id=randomUUID();db.prepare('INSERT INTO events VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(id,req.user.id,name,description||'',venue||'',latitude,longitude,radius,start_time,end_time,'upcoming',new Date().toISOString());res.json(db.prepare('SELECT * FROM events WHERE id=?').get(id))});
app.patch('/api/events/:id/status',auth,(req,res)=>{const e=db.prepare('SELECT * FROM events WHERE id=?').get(req.params.id);if(!e||e.organizer_id!==req.user.id)return res.status(404).json({message:'Event not found'});db.prepare('UPDATE events SET status=? WHERE id=?').run(req.body.status,e.id);res.json({ok:true})});
app.get('/api/events/:id',(req,res)=>{const e=db.prepare('SELECT * FROM events WHERE id=?').get(req.params.id);if(!e)return res.status(404).json({message:'Event not found'});const stats=db.prepare(`SELECT SUM(status='present') present,SUM(status='rejected') rejected,COUNT(*) total FROM attendance WHERE event_id=?`).get(e.id);const recent=db.prepare(`SELECT a.*,u.name,u.email FROM attendance a JOIN users u ON u.id=a.user_id WHERE a.event_id=? ORDER BY a.marked_at DESC LIMIT 12`).all(e.id);res.json({...e,stats:{present:stats.present||0,rejected:stats.rejected||0},recent})});

app.get('/api/events/:id/qr',auth,async(req,res)=>{const e=db.prepare('SELECT * FROM events WHERE id=?').get(req.params.id);if(!e)return res.status(404).json({message:'Event not found'});const token=randomUUID()+'.'+Date.now();const exp=Date.now()+15000;db.prepare('INSERT INTO qr_tokens VALUES (?,?,?,?,?)').run(randomUUID(),e.id,token,exp,new Date().toISOString());const payload=JSON.stringify({eventId:e.id,token});const data=await QRCode.toDataURL(payload,{width:520,margin:2,errorCorrectionLevel:'H'});res.json({data,expiresAt:exp,eventId:e.id})});

app.post('/api/attendance/verify',auth,(req,res)=>{const {eventId,token,latitude,longitude}=req.body;const e=db.prepare('SELECT * FROM events WHERE id=?').get(eventId);if(!e)return res.status(404).json({message:'Event not found'});const qr=db.prepare('SELECT * FROM qr_tokens WHERE event_id=? AND token=? ORDER BY created_at DESC LIMIT 1').get(eventId,token);const nowMs=Date.now();if(!qr||nowMs>qr.expires_at){audit(eventId,req.user.id,'REJECTED','Expired or invalid QR token');return res.status(400).json({ok:false,reason:'QR code expired. Please scan the live QR again.'})}if(nowMs<new Date(e.start_time).getTime()||nowMs>new Date(e.end_time).getTime()){audit(eventId,req.user.id,'REJECTED','Outside event time window');return res.status(400).json({ok:false,reason:'This event is not currently accepting attendance.'})}const existing=db.prepare('SELECT * FROM attendance WHERE event_id=? AND user_id=?').get(eventId,req.user.id);if(existing){audit(eventId,req.user.id,'REJECTED','Duplicate attendance attempt');return res.status(409).json({ok:false,reason:'Attendance already marked for this event.',duplicate:true})}const d=distance(e.latitude,e.longitude,Number(latitude),Number(longitude));if(d>e.radius){audit(eventId,req.user.id,'REJECTED',`Outside radius: ${Math.round(d)}m`);db.prepare('INSERT OR IGNORE INTO attendance VALUES (?,?,?,?,?,?,?,?,?)').run(randomUUID(),eventId,req.user.id,new Date().toISOString(),latitude,longitude,d,'rejected','qr+geo');return res.status(403).json({ok:false,reason:`You are ${Math.round(d)}m away. Required: within ${e.radius}m.`,distance:d})}const now=new Date().toISOString();db.prepare('INSERT INTO attendance VALUES (?,?,?,?,?,?,?,?,?)').run(randomUUID(),eventId,req.user.id,now,latitude,longitude,d,'present','qr+geo');audit(eventId,req.user.id,'PRESENT',`Verified at ${Math.round(d)}m`);const user=db.prepare('SELECT name,email FROM users WHERE id=?').get(req.user.id);io.to(`event:${eventId}`).emit('attendance:new',{name:user.name,email:user.email,marked_at:now,distance:d,status:'present'});res.json({ok:true,message:'Attendance verified',distance:d,markedAt:now})});
app.get('/api/events/:id/report',auth,(req,res)=>{const e=db.prepare('SELECT * FROM events WHERE id=?').get(req.params.id);if(!e)return res.status(404).end();const rows=db.prepare(`SELECT u.name,u.email,a.status,a.marked_at,a.distance,a.verification FROM attendance a JOIN users u ON u.id=a.user_id WHERE a.event_id=? ORDER BY a.marked_at`).all(e.id);const registered=db.prepare('SELECT COUNT(*) c FROM users WHERE role="attendee"').get().c;res.json({event:e,registered,rows})});
app.get('/api/events/:id/audit',auth,(req,res)=>res.json(db.prepare('SELECT l.*,u.name FROM audit_logs l LEFT JOIN users u ON u.id=l.user_id WHERE l.event_id=? ORDER BY timestamp DESC LIMIT 100').all(req.params.id)));
app.get('/api/dashboard',auth,(req,res)=>{const events=db.prepare('SELECT * FROM events WHERE organizer_id=?').all(req.user.id);const present=db.prepare('SELECT COUNT(*) c FROM attendance a JOIN events e ON e.id=a.event_id WHERE e.organizer_id=? AND a.status="present"').get(req.user.id).c;const rejected=db.prepare('SELECT COUNT(*) c FROM audit_logs l JOIN events e ON e.id=l.event_id WHERE e.organizer_id=? AND l.action="REJECTED"').get(req.user.id).c;const recent=db.prepare(`SELECT a.*,u.name,e.name event_name FROM attendance a JOIN users u ON u.id=a.user_id JOIN events e ON e.id=a.event_id WHERE e.organizer_id=? ORDER BY a.marked_at DESC LIMIT 8`).all(req.user.id);res.json({events:events.length,present,rejected,recent})});

io.on('connection',socket=>{socket.on('event:join',id=>socket.join(`event:${id}`))});
const port=process.env.PORT||5000;http.listen(port,()=>console.log(`ATTENDX API running on http://localhost:${port}`));
